parameters:
    fpdf.core.class: FPDF
    fpdf.html.class: FPDFHTML
    fpdf.factory.class: Mayeco\fPDFBundle\Factory\fPDFFactory

services:
    fpdf:
        class:              "%fpdf.core.class%"
        factory_class:      "%fpdf.factory.class%"
        factory_method:     get

    fpdf.html:
        class:              "%fpdf.html.class%"
        factory_class:      "%fpdf.factory.class%"
        factory_method:     getHtml
